- hosts: localhost
  vars_files:
    - project.yaml
  tasks:
    ## apt
    - name: apt repo
      apt_repository:
        repo: ppa:ondrej/php
      become: yes

    - name: apt install
      apt:
        name:
          [
            zsh,
            direnv,
            pipenv,
            php7.3,
            php7.3-pgsql,
            php7.3-mbstring,
            php7.3-gd,
            postgresql,
            python3-psycopg2,
            apache2,
            php-xdebug,
          ]
      become: yes

    ## apache setting
    - name: enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes

    - name: enable apache2 ssl
      apache2_module:
        name: ssl
        state: present
      become: yes

    - name: apache config
      template:
        src: site.conf
        dest: /etc/apache2/sites-available/
      become: yes

    - name: enable site.conf
      shell: a2ensite site.conf
      become: yes

    ## php config
    - name: xdebug config
      template:
        src: xdebug.ini
        dest: /etc/php/7.3/mods-available/
      become: yes

    - name: enable xdebug
      shell: phpenmod xdebug
      become: yes

    ## reload
    - name: restart httpd
      service:
        name: apache2
        state: restarted
      become: yes

    ## postgres setup
    - name: config pg_hba.conf
      template:
        src: pg_hba.conf
        dest: /etc/postgresql/12/main/
      become: yes
      become_user: postgres

    - name: start postgres
      service:
        name: postgresql
        state: started
        enabled: true
      become: yes

    - name: create database
      postgresql_db:
        name: "{{ pg_database }}"
        encoding: "UTF-8"
        template: template0
        state: present
      become: yes
      become_user: postgres

    - name: create user
      postgresql_user:
        db: "{{ pg_database }}"
        name: "{{ pg_username }}"
        password: "{{ pg_password }}"
        priv: ALL
        state: present
        login_user: postgres
      become: yes
      become_user: postgres

    ## database provisioner
    - name: database provision script
      template:
        src: dbinit.sh
        dest: "{{ ansible_env.HOME }}"
        mode: 0755
    - name: start script
      template:
        src: start.sh
        dest: "{{ ansible_env.HOME }}"
        mode: 0755
